model_metadata:
# Mandatory Fields
  model_uid: RN8Sr8dWeUQuf6Ors7xK
  model_creation_date: 2019-02-19 01:23:51 #UTC Time Zone
  model_author: harel.l
  model_parent: 
  model_name: mtcars-example
# Optional Fields
parameters: 
