model_metadata:
# Mandatory Fields
  model_uid: UsVMyTnqrWHbJq4HCv7X
  model_creation_date: 2019-02-18 23:08:29 #UTC Time Zone
  model_author: harel.l
  model_parent: 
  model_name: mtcars-example
# Optional Fields
parameters: 
