model_metadata:
# Mandatory Fields
  model_uid: LkC1kkuaIFjgKGVIseQu
  model_creation_date: 2019-02-17 19:47:36 #UTC Time Zone
  model_author: harel.l
  model_parent: 
  model_name: mtcars-example
# Optional Fields
parameters: 
