packages:
  CRAN:
  - assertive (>= 0.3-5)
  - dplyr (>= 0.7.4)
  - jsonlite (>= 1.6)
  - magrittr (>= 1.5)
  - purrr (>= 0.2.5)
  - remotes (>= 2.0.2)
  - rsample (>= 0.0.3)
  - stringr (>= 1.3.1)
  - tibble (>= 1.4.2)
  - whisker (>= 0.3-2)
  - yaml (>= 2.2.0)
  - knitr
  - rmarkdown
  - testthat
  - tidyverse
  - foreach
  GitHub:
  - tidyverse/lubridate
  - tidyverse/forcats

