---
title: "DALEX Notebook"
author: ""
date: "12 June 2018"
output: 
  html_notebook: 
    df_print: kable
    code_folding: hide
    highlight: tango
    theme: journal
    toc: yes
---

```{r setup, include=FALSE}
#######################
# Global Code Options #
#######################
knitr::opts_chunk$set(echo = TRUE, results = 'hide', tidy = TRUE,
                      cache = FALSE, prompt = FALSE,
                      comment = NA, message = FALSE, warning = FALSE)
#'
########################################
# Load Project Libraries and Functions #
########################################
k_path_project <<- rprojroot::find_rstudio_root_file()
source(file.path(k_path_project, "code", "scripts", "setup.R"))
```

# Data pipeline

```{r get_titanic_data}
titanic_raw <- get_titanic_raw_data()
```

```{r tidy_the_data}
titanic_tidy <- 
    titanic_raw %>%
    # Convert the target variable to factor 
    mutate(Survived = factor(Survived, 
                             levels = 0:1, labels = c("No", "Yes"))) %>%
    # Convert character variables to factor
    mutate_if(is.character, as.factor) %>%
    # Select variables
    select(Set, Survived, Sex, Age) %>%
    # Impute missing values
    mutate(Age = ifelse(Age %>% is.na, 20, Age))
assert_all_are_not_na(titanic_tidy %>% select(-Survived))
assert_is_factor(titanic_tidy %>% .$Survived)
```

```{r split_the_data}
train_tidy <- titanic_tidy %>% dplyr::filter(Set %in% "train") %>% select(-Set)
test_tidy <- titanic_tidy %>%  dplyr::filter(Set %in% "test") %>% select(-Set)
```

# Fit models to the training set

```{r fit_models, results='markup'}
mdl_logreg <- glm(Survived ~ Age, family = binomial, data = train_tidy)
mdl_rf <- randomForest(Survived ~ Age, data = train_tidy, ntree = 100)
# mdl_logreg %>% broom::tidy()
# mdl_logreg %>% broom::glance() 
# mdl_logreg %>% broom::augment()
```

# DALEX 

## The explain() function

```{r the_explain_function, echo=TRUE}
explain_logreg <- 
    DALEX::explain(mdl_logreg,
                   label="logistic_regression",
                   data = train_tidy, y = train_tidy$Survived)
explain_rf <- 
    DALEX::explain(mdl_rf,
                   label="random_forest",
                   data = train_tidy, y = train_tidy$Survived)
```

## The model_performance() function

```{r the_model_performance_function, echo=TRUE}
# mp_logreg <- DALEX::model_performance(explain_logreg)
# mp_rf <- DALEX::model_performance(explain_rf)
```

```{r, results='markup', out.width = "100%", dpi = 200, fig.height = 8}
# print(explain_logreg)
# plot(mp_logreg, mp_rf)
```

## The variable_response() function

```{r the_variable_response_function, echo=TRUE}
pdp_logreg <- variable_response(explain_logreg, variable = "Age", type = "pdp")
pdp_rf <- variable_response(explain_rf, variable = "Age", type = "pdp")
```

```{r, out.width = "100%", dpi = 200, fig.height = 8}
plot(pdp_logreg, pdp_rf)
```